### ISSUE TITLE
Improve linear flow syntax

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/lowscript#21]
Example:

# Order product

* Form `Order`
* Reservation
  * `+` Notify "Reservation was successful"
  * `-` Notify "The product is out of stock"
* Form `Payment`
* Payment
  * `+` Notify "Payment was successful"
  * `<` Return payment
* Pick up from the warehouse
  * `<` Return to the warehouse
* Shipping by carrier
  * `+` Notify "The product was successfully sent"
  * `-` Notify "The product was not sent"
* Finalization
  * `+` Notify "Please provide product feedback"
  * `+` Notify "Please provide service feedback"

Source of this example:
```
# Order product

* Form `Order`
* Reservation
  * `+` Notify "Reservation was successful"
  * `-` Notify "The product is out of stock"
* Form `Payment`
* Payment
  * `+` Notify "Payment was successful"
  * `<` Return payment
* Pick up from the warehouse
  * `<` Return to the warehouse
* Shipping by carrier
  * `+` Notify "The product was successfully sent"
  * `-` Notify "The product was not sent"
* Finalization
  * `+` Notify "Please provide product feedback"
  * `+` Notify "Please provide service feedback"
```

**Comment by leonpolak** [comment]
No problem
